### ISSUE TITLE
how is the button connected?

### ISSUE THREAD

**Issue by evanthebouncy** [DriveCurrent/photo-picker#2]
```
@IBOutlet weak var takePhotoButton: UIButton!
```

the variable takePhotoButton is not being used anywhere in the code, nor does anywhere in the code mentions the button at all. I'm confused...

It feels like this code has some divergence to the explanation in the blog post.
for instance, this code fragment

```
@IBAction func didPressTakePhoto(sender: UIButton) {
}
```

is shown in the blog post, but instead here it became

```
@IBAction func didPressTakePhoto(sender: AnyObject) {
}
```

And I don't really know what effect it has.

I'm sure it's all very clear for someone who's been coding ios for awhile but it is confusing to me still.

**Comment by araustin** [comment]
You're right, the takePhotoButton variable is not used and should be removed.

The difference between the function signatures does not have an effect as the code stands, since `sender` is not referenced in the function body. However, if `sender` was referenced, it would by default behave as the type declared in the function signature. So if `sender` is a UIButton, you would get button functionality. If it is AnyObject, you would have to cast it to a UIButton if you wanted to use some button functionality.
